version: "3.7"

services:

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik.local"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.4.2"
    container_name: "elasticsearch.local"
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
    environment:
      - discovery.type=single-node
    networks:
      - traefik
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.4.2"
    container_name: "kibana.local"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch.local:9200
    depends_on:
      - elasticsearch
    networks:
      - traefik
  kafka:
    image: "spotify/kafka"
    container_name: "kafka.local"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ADVERTISED_HOST=kafka.local
      - ADVERTISED_PORT=9092
    networks:
      - traefik
#no reconnecta al storage, buscar delay o auto-reconnect
  jaeger-collector:
    image: "jaegertracing/jaeger-collector:1.15"
    container_name: "jaeger-collector.local"
    command:
      - "--log-level=debug"
    ports:
      - "14250/udp"
    depends_on:
      - kafka
    environment:
      - SPAN_STORAGE_TYPE=kafka
      - KAFKA_PRODUCER_BROKERS=kafka.local:9092
      - KAFKA_PRODUCER_TOPIC=tracing
      - KAFKA_PRODUCER_ENCODING=json
    networks:
      - traefik
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master.local
    ports:
      - "9080:8080"
      - "7077:7077"
    networks:
      - traefik
  spark-worker:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master.local:7077"
    networks:
      - traefik
  jaeger-agent:
    image: "jaegertracing/jaeger-agent:1.15"
    container_name: "jaeger-agent.local"
    command:
      - "--reporter.grpc.host-port=jaeger-collector.local:14250"
      - "--log-level=debug"
    depends_on:
      - kafka
      - jaeger-collector
    # environment:
    #   - JAEGER_USER=alan
    #   - JAEGER_PASSWORD=alan
    ports:
      - "5775:5775"
    networks:
      - traefik

networks:
  traefik:
    name: traefik-nt
    driver: bridge
#docker run -d -p 8080:8080 -p 80:80 -v //var/run/docker.dock:/var/run/docker.sock -v ./traefik.toml:/etc/traefik/traefik.toml --network traefik-nt --name traefik traefik:v2.0.0-rc3
